injectWorkspacePackages: true

minimumReleaseAge: 10080
minimumReleaseAgeIgnoreMissingTime: false
minimumReleaseAgeExclude:
  - '@millicast/*'
trustPolicy: no-downgrade
trustPolicyExclude:
  - ua-parser-js@1.0.41
engineStrict: true

allowBuilds:
  '@parcel/watcher': true
