name: npm run build
description: Shared npm build step

inputs:
  ref:
    description: 'git reference to checkout'
    required: false

runs:
  using: composite
  steps:
    - uses: actions/checkout@v6
      with:
        ref: ${{ inputs.ref }}

    - name: 'npm run build'
      shell: 'sh -e -o pipefail {0}'
      run: |        
        npm ci
        npm run build

        printf '\nNODE: %s\nNPM: %s\n\n' "$(node --version)" "$(npm --version)"
