name: 'Build dryrun'

on:
  workflow_dispatch:
  push:
    tags:
      - '**'
    branches:
      - '**'

jobs:
  build_deploy:
    uses: ./.github/workflows/npm-build-publish.yml
    with:
      ref: ${{ github.ref }}
      dryrun: true
