name: 'RELEASE: Bump version, create tag/release, and npm publish'

on:
  workflow_dispatch:
    inputs:
      bump_version:
        type: choice
        required: true
        description: Which part of version to bump
        options:
          - patch
          - minor
          - major

jobs:
#  next-version:
#    uses: millicast/github-actions/.github/workflows/npm-version-release.yml@feature/node-release_workflow
#    # should ONLY be used from main
#    #if: github.ref_name == 'main'
#    secrets: inherit
#    permissions:
#      contents: write
#    with:
#      bump_version: ${{ inputs.bump_version }}

  build:
    uses: ./.github/workflows/_build.yml
    #needs: [next-version]
    permissions:
      contents: read
      id-token: write
    with:
      ref: ${{ github.ref_name }}
