name: npm-build-publish

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'git reference to checkout'
        required: true
        type: string
      npm_tag:
        description: 'npm tag to publish package to'
        required: false
        type: string
  workflow_call:
    inputs:
      ref:
        required: true
        type: string
      npm_tag:
        required: false
        type: string

jobs:
  build-publish:
    name: "build-publish ${{ inputs.ref }}"
    runs-on: ubuntu-latest
    container: node:24-alpine
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ inputs.ref }}

      - name: "npm run build && npm publish"
        env:
          npm_tag: ${{ inputs.npm_tag }}
        run: |
          set --
          if [ -n "${npm_tag}" ]; then
            set -- "$@" --tag "${npm_tag}"
          fi

          npm ci
          npm run build
          npm publish --provenance "$@"
